timeout support added
appknox/appknox-go pull request #54
Opened 2024-11-26 16:33 UTC by ginilpg

| Title                          | Value                                                                                     |
| ------------------------------ | ----------------------------------------------------------------------------------------- |
| **Type**                       | Feature                                                |
| **Ticket/Issue**               | https://appknox.atlassian.net/browse/PD-1604                                   |
| **Migrations**                 | No / &lt;apps introducing migrations (eg: `core`, `organization`)&gt;                     |
| **Migration&nbsp;Scripts**     | No / Yes (provide script in description)                                                  |
| **ENV&nbsp;vars&nbsp;change**  | No / &lt;list of env vars added or removed (eg: `APPKNOX_SAMPLE_ENV=local_dev_value`)&gt; |
| **Frontend**                   | No / [&lt;irene PR link&gt;](#)                                                           |
| **Local&nbsp;testing**         | Pending / Done                                                                            |
| **Staging&nbsp;testing**       | Pending / Skip / [&lt;preview link&gt;](#)                                                |
| **On&nbsp;premise&nbsp;notes** | NA / &lt;any notes specific to on premise deployments&gt;                                 |
| **Documentation**              | None / [&lt;Confluence design specification document link&gt;](#)                         |
| **Release&nbsp;notes**         | None / [&lt;Confluence changelog document link&gt;](#)                                    |
| **Version&nbsp;upgrade**       |  Minor                                                                      |

---

### Changelog

1. Added an option to override default 30 mins timeout using cicheck command

---

#### Dependent PRs

-   [Link to vendor#N](#)
-   [Link to k8s](#), etc.

2024-12-05 12:15 UTC, cosmosgenius requested changes

2024-12-05 12:15 UTC, cosmosgenius commented on cmd/cicheck.go
> +		timeoutMinutes, _ := cmd.Flags().GetInt("sast-timeout")
```suggestion
		timeoutMinutes, _ := cmd.Flags().GetInt("timeout")
```
should be timeout instead.

2024-12-11 09:04 UTC, ginilpg commented on cmd/cicheck.go
> +		timeoutMinutes, _ := cmd.Flags().GetInt("sast-timeout")
> should be timeout instead.

This has been resolved

2024-12-12 09:43 UTC, cosmosgenius approved these changes

2024-12-12 09:43 UTC, merged